USE [master]
GO
/****** Object:  Database [PTUD-JOJO-Restaurant]    Script Date: 2025-10-01 2:46:28 PM ******/
CREATE DATABASE [PTUD-JOJO-Restaurant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PTUD-JOJO-Restaurant', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PTUD-JOJO-Restaurant.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PTUD-JOJO-Restaurant_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PTUD-JOJO-Restaurant_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PTUD-JOJO-Restaurant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ARITHABORT OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET  MULTI_USER 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET QUERY_STORE = ON
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PTUD-JOJO-Restaurant]
GO
/****** Object:  Table [dbo].[BAN]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAN](
	[maBan] [nchar](10) NOT NULL,
	[soCho] [int] NOT NULL,
	[makhuVuc] [nchar](10) NOT NULL,
	[trangThai] [nchar](10) NOT NULL,
 CONSTRAINT [PK_BAN] PRIMARY KEY CLUSTERED 
(
	[maBan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETPHIEUDATBAN]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETPHIEUDATBAN](
	[maMonAn] [nchar](10) NOT NULL,
	[maPhieu] [nchar](10) NOT NULL,
	[soLuongMonAn] [int] NOT NULL,
	[ghiChu] [nvarchar](max) NULL,
 CONSTRAINT [PK_CHITIETPHIEUDATBAN] PRIMARY KEY CLUSTERED 
(
	[maMonAn] ASC,
	[maPhieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETHOADON]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETHOADON](
	[maHoaDon] [nchar](10) NOT NULL,
	[maMonAn] [nchar](10) NOT NULL,
	[soLuong] [int] NOT NULL,
	[donGia] [money] NOT NULL,
 CONSTRAINT [PK_CHITIETHOADON_1] PRIMARY KEY CLUSTERED 
(
	[maHoaDon] ASC,
	[maMonAn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[maHoaDon] [nchar](10) NOT NULL,
	[maKhachHang] [nchar](10) NOT NULL,
	[ngayLap] [date] NOT NULL,
	[phuongThuc] [varchar](50) NOT NULL,
	[maKhuyenMai] [nchar](10) NULL,
	[maThue] [nchar](10) NOT NULL,
	[gioVao] [datetime] NOT NULL,
	[gioRa] [datetime] NOT NULL,
	[maNhanVien] [nchar](7) NOT NULL,
	[maPhieu] [nchar](10) NULL,
 CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED 
(
	[maHoaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[maKhachHang] [nchar](10) NOT NULL,
	[tenKhachHang] [nvarchar](50) NOT NULL,
	[sdt] [nchar](10) NOT NULL,
	[email] [nvarchar](50) NULL,
	[diemTichLuy] [int] NOT NULL,
	[laThanhVien] [bit] NOT NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[maKhachHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHUVUC]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHUVUC](
	[maKhuVuc] [nchar](10) NOT NULL,
	[tenKhuVuc] [varchar](50) NOT NULL,
	[moTa] [varchar](max) NULL,
	[trangThai] [bit] NOT NULL,
 CONSTRAINT [PK_KHUVUC] PRIMARY KEY CLUSTERED 
(
	[maKhuVuc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHUYENMAI]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHUYENMAI](
	[maKhuyenMai] [nchar](10) NOT NULL,
	[tenKhuyenMai] [nvarchar](50) NULL,
	[giaTri] [float] NULL,
	[thoiGianBatDau] [date] NOT NULL,
	[thoiGianKetThuc] [date] NOT NULL,
 CONSTRAINT [PK_KHUYENMAI] PRIMARY KEY CLUSTERED 
(
	[maKhuyenMai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONAN]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONAN](
	[maMonAn] [nchar](10) NOT NULL,
	[tenMonAn] [nvarchar](50) NOT NULL,
	[donGia] [money] NOT NULL,
	[trangThai] [bit] NOT NULL,
 CONSTRAINT [PK_MONAN] PRIMARY KEY CLUSTERED 
(
	[maMonAn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[maNV] [nchar](7) NOT NULL,
	[tenNhanVien] [nvarchar](50) NOT NULL,
	[gioiTinh] [bit] NOT NULL,
	[sdt] [nchar](10) NOT NULL,
	[email] [varchar](50) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[maNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUDATBAN]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUDATBAN](
	[maPhieu] [nchar](10) NOT NULL,
	[thoiGianDat] [datetime] NOT NULL,
	[maKhachHang] [nchar](10) NOT NULL,
	[maNV] [nchar](7) NOT NULL,
	[maBan] [nchar](10) NOT NULL,
	[tienCoc] [money] NULL,
 CONSTRAINT [PK_PHIEUDATBAN] PRIMARY KEY CLUSTERED 
(
	[maPhieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[maNV] [nchar](7) NOT NULL,
	[tenDangNhap] [nchar](10) NOT NULL,
	[matKhau] [nvarchar](50) NOT NULL,
	[vaiTro] [nchar](10) NOT NULL,
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY CLUSTERED 
(
	[maNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THUE]    Script Date: 2025-10-01 2:46:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THUE](
	[maSoThue] [nchar](10) NOT NULL,
	[tenThue] [nchar](10) NOT NULL,
	[tyLeThue] [float] NOT NULL,
 CONSTRAINT [PK_THUE] PRIMARY KEY CLUSTERED 
(
	[maSoThue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BAN]  WITH CHECK ADD  CONSTRAINT [FK_BAN_KHUVUC] FOREIGN KEY([makhuVuc])
REFERENCES [dbo].[KHUVUC] ([maKhuVuc])
GO
ALTER TABLE [dbo].[BAN] CHECK CONSTRAINT [FK_BAN_KHUVUC]
GO
ALTER TABLE [dbo].[CHITIETPHIEUDATBAN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUDATBAN_MONAN] FOREIGN KEY([maMonAn])
REFERENCES [dbo].[MONAN] ([maMonAn])
GO
ALTER TABLE [dbo].[CHITIETPHIEUDATBAN] CHECK CONSTRAINT [FK_CHITIETPHIEUDATBAN_MONAN]
GO
ALTER TABLE [dbo].[CHITIETPHIEUDATBAN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUDATBAN_PHIEUDATBAN] FOREIGN KEY([maPhieu])
REFERENCES [dbo].[PHIEUDATBAN] ([maPhieu])
GO
ALTER TABLE [dbo].[CHITIETPHIEUDATBAN] CHECK CONSTRAINT [FK_CHITIETPHIEUDATBAN_PHIEUDATBAN]
GO
ALTER TABLE [dbo].[CHITIETHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETHOADON_HOADON] FOREIGN KEY([maHoaDon])
REFERENCES [dbo].[HOADON] ([maHoaDon])
GO
ALTER TABLE [dbo].[CHITIETHOADON] CHECK CONSTRAINT [FK_CHITIETHOADON_HOADON]
GO
ALTER TABLE [dbo].[CHITIETHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETHOADON_MONAN] FOREIGN KEY([maMonAn])
REFERENCES [dbo].[MONAN] ([maMonAn])
GO
ALTER TABLE [dbo].[CHITIETHOADON] CHECK CONSTRAINT [FK_CHITIETHOADON_MONAN]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY([maKhachHang])
REFERENCES [dbo].[KHACHHANG] ([maKhachHang])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_KHACHHANG]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_KHUYENMAI] FOREIGN KEY([maKhuyenMai])
REFERENCES [dbo].[KHUYENMAI] ([maKhuyenMai])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_KHUYENMAI]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_NHANVIEN] FOREIGN KEY([maNhanVien])
REFERENCES [dbo].[NHANVIEN] ([maNV])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_NHANVIEN]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_THUE] FOREIGN KEY([maThue])
REFERENCES [dbo].[THUE] ([maSoThue])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_THUE]
GO
ALTER TABLE [dbo].[PHIEUDATBAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATBAN_BAN] FOREIGN KEY([maBan])
REFERENCES [dbo].[BAN] ([maBan])
GO
ALTER TABLE [dbo].[PHIEUDATBAN] CHECK CONSTRAINT [FK_PHIEUDATBAN_BAN]
GO
ALTER TABLE [dbo].[PHIEUDATBAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATBAN_KHACHHANG] FOREIGN KEY([maKhachHang])
REFERENCES [dbo].[KHACHHANG] ([maKhachHang])
GO
ALTER TABLE [dbo].[PHIEUDATBAN] CHECK CONSTRAINT [FK_PHIEUDATBAN_KHACHHANG]
GO
ALTER TABLE [dbo].[PHIEUDATBAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATBAN_NHANVIEN] FOREIGN KEY([maNV])
REFERENCES [dbo].[NHANVIEN] ([maNV])
GO
ALTER TABLE [dbo].[PHIEUDATBAN] CHECK CONSTRAINT [FK_PHIEUDATBAN_NHANVIEN]
GO
ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TAIKHOAN_NHANVIEN] FOREIGN KEY([maNV])
REFERENCES [dbo].[NHANVIEN] ([maNV])
GO
ALTER TABLE [dbo].[TAIKHOAN] CHECK CONSTRAINT [FK_TAIKHOAN_NHANVIEN]
GO
USE [master]
GO
ALTER DATABASE [PTUD-JOJO-Restaurant] SET  READ_WRITE 
GO
